version: '3.1'
services:
  product-database:
    container_name: product-database
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./_dist/product-database-data:/data/db
