version: '3.1'
services:
  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./_dist/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--http-port 8084", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8084:8084"
    expose:
      - "8084"
    volumes:
      - ./_dist/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  # PRODUCT DATABASE
  product-database:
    container_name: product-database
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./_dist/product-database-data:/data/db

  # INVENTORY DATABASE
  inventory_database:
    image: postgres
    container_name: inventory_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=inventory_database
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=0199
      - PGDATA=/data/postgres
    ports:
      - "5431:5431"
    expose:
      - "5431"
    volumes:
      - ./_dist/inventory_database:/data/postgres
    command: -p 5431

  # ORDER DATABASE
  order_database:
    image: postgres
    container_name: order_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=order_database
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=0199
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./_dist/order_database:/data/postgres
    command: -p 5432


