version: '3.1'
services:
# PRODUCT DATABASE
  product-database:
    container_name: product-database
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./_dist/product-database-data:/data/db

  # INVENTORY DATABASE
  inventory_database:
    image: postgres
    container_name: inventory_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=inventory_database
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=0199
      - PGDATA=/data/postgres
    ports:
      - "5431:5431"
    expose:
      - "5431"
    volumes:
      - ./_dist/inventory_database:/data/postgres
    command: -p 5431

# ORDER DATABASE
  order_database:
    image: postgres
    container_name: order_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=order_database
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=0199
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./_dist/order_database:/data/postgres
    command: -p 5432


