version: '3.1'
services:
  # zookeeper configuration
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # broker configuration
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    expose:
      - "9092"
      - "29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ## Keycloak Config with Mysql database
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./_dist/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    command: [ "start-dev", "--http-port 9090", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:9090"
    expose:
      - "9090"
    volumes:
      - ./_dist/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql

  # zipkin configuration
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    expose:
      - "9411"

  # PRODUCT DATABASE
  product-database:
    container_name: product-database
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./_dist/product-database-data:/data/db

  # INVENTORY DATABASE
  inventory_database:
    image: postgres
    container_name: inventory_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=inventory_database
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=0199
      - PGDATA=/data/postgres
    ports:
      - "5431:5431"
    expose:
      - "5431"
    volumes:
      - ./_dist/inventory_database:/data/postgres
    command: -p 5431

  # ORDER DATABASE
  order_database:
    image: postgres
    container_name: order_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=order_database
      - POSTGRES_USER=order_user
      - POSTGRES_PASSWORD=0199
      - PGDATA=/data/postgres
    ports:
      - "5430:5430"
    expose:
      - "5430"
    volumes:
      - ./_dist/order_database:/data/postgres
    command: -p 5430


