apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-database
  name: inventory-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-database
  template:
    metadata:
      labels:
        app: inventory-database
    spec:
      containers:
        - args:
            - -p
            - "5431"
          image: postgres
          name: inventory-database
          ports:
            - containerPort: 5431
          env:
            - name: PGDATA
              value: "/data/postgres"
            - name: POSTGRES_DB
              value: "inventory-database"
            - name: POSTGRES_PASSWORD
              value: "0199"
            - name: POSTGRES_USER
              value: "inventory_user"
          resources: { }
          volumeMounts:
            - mountPath: /data/postgres
              name: inventory-database-claim0
      restartPolicy: Always
      volumes:
        - name: inventory-database-claim0
          persistentVolumeClaim:
            claimName: inventory-database-claim0

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: inventory-database
  name: inventory-database
spec:
  ports:
    - name: "5431"
      port: 5431
      targetPort: 5431
  selector:
    app: inventory-database
status:
  loadBalancer: { }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: inventory-database-claim0
  name: inventory-database-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: { }