server:
  port: 8083

spring:
  application:
    name: product-service
  data:
    mongodb:
      port: 27017
      host: localhost
      uri: mongodb://localhost:27017/product-database

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

