server:
  port: 8081

spring:
  application:
    name: inventory-service
  datasource:
    username: inventory_user
    password: 0199
    url: jdbc:postgresql://localhost:5431/inventory_database
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
